//
// Record.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Record: Codable {

    public var id: String?
    public var co2: Double?
    public var temp: Double?
    public var date: String?

    public init() {}

}
