//
// RecordAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class RecordAPI {
    /**
     * enum for parameter print
     */
    public enum Print_list: String { 
        case notformated = "notFormated"
        case pretty = "pretty"
        case silent = "silent"
    }

    /**
     Read all tracked records
     
     - parameter print: (query) json prety print 
     - parameter orderBy: (query) date (json primitive string) with quotes (optional, default to date)
     - parameter startAt: (query) date (json primitive string) with quotes (optional, default to 2017-11-11 13)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func list(print: [String], orderBy: String? = nil, startAt: String? = nil, completion: @escaping ((_ data: [String:Record]?,_ error: Error?) -> Void)) {
        listWithRequestBuilder(print: print, orderBy: orderBy, startAt: startAt).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Read all tracked records
     - GET /records.json
     - Filter by date
     - examples: [{contentType=application/xml, example=<null>
  <id>aeiou</id>
  <co2>1.3579</co2>
  <temp>1.3579</temp>
  <date>aeiou</date>
</null>}, {contentType=application/json, example=[ {
  "date" : "aeiou",
  "temp" : 6.02745618307040320615897144307382404804229736328125,
  "co2" : 0.80082819046101150206595775671303272247314453125,
  "id" : "aeiou"
} ]}]
     - examples: [{contentType=application/xml, example=<null>
  <id>aeiou</id>
  <co2>1.3579</co2>
  <temp>1.3579</temp>
  <date>aeiou</date>
</null>}, {contentType=application/json, example=[ {
  "date" : "aeiou",
  "temp" : 6.02745618307040320615897144307382404804229736328125,
  "co2" : 0.80082819046101150206595775671303272247314453125,
  "id" : "aeiou"
} ]}]
     
     - parameter print: (query) json prety print 
     - parameter orderBy: (query) date (json primitive string) with quotes (optional, default to date)
     - parameter startAt: (query) date (json primitive string) with quotes (optional, default to 2017-11-11 13)

     - returns: RequestBuilder<[String:Record]> 
     */
    open class func listWithRequestBuilder(print: [String], orderBy: String? = nil, startAt: String? = nil) -> RequestBuilder<[String:Record]> {
        let path = "/records.json"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "print": print, 
            "orderBy": orderBy, 
            "startAt": startAt
        ])
        

        let requestBuilder: RequestBuilder<[String:Record]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
